name: Publish Python Package

on:
  push:
    branches:
      - master  # ou a branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # ou outra versão que você esteja usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt  # Instala dependências listadas no requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Build package
        if: success()
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
